[project]
name = "rust-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Mislav Novakovic", email = "mislav.novakovic@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[tool.maturin]
module-name = "rust_server._core"
python-packages = ["rust_server"]
python-source = "src"

# Non default options

# "xetnsions-module" tells pyo3 we want to build an extension module, skip linking against lipython.so
features = ["pyo3/extension-module"]
# bindings type
bindings = "pyo3"
# Control the platform tag on Linux
compatibility = "manylinux2014"
skip-auditwheel = false
# Reduce binary size
strip = true
include = [
    "rust-toolchain.toml"
]
